DROP DATABASE IF EXISTS NotePass;
CREATE DATABASE NotePass;
USE Notepass;

DROP TABLE IF EXISTS Users;
CREATE TABLE Users (
    UserID INT NOT NULL AUTO_INCREMENT,
    Username VARCHAR(256) NOT NULL,
    Email VARCHAR(256) NOT NULL,
    School VARCHAR(256) NOT NULL,
    PRIMARY KEY(UserID)
)

DROP TABLE IF EXISTS Passwords;
CREATE TABLE Passwords (
    UserID INT NOT NULL,
    Password VARCHAR(256) NOT NULL,
    FOREIGN KEY (UserID) REFERENCES Users(UserID) ON DELETE CASCADE,
    PRIMARY KEY(UserID)
)
